import { Document, Page, Text, View, Link, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import React from 'react';
import type { DailyReport, SummaryReport } from './data';

// Branded PDF exports (PRD §10/§11.4). Uses built-in Helvetica (no font files).
const C = { gold: '#F5C400', ink: '#1A1A1A', muted: '#666', line: '#DDD', green: '#2e7d32' };

const s = StyleSheet.create({
  page: { padding: 28, fontSize: 10, color: C.ink, fontFamily: 'Helvetica' },
  band: { backgroundColor: C.gold, padding: 10, borderRadius: 4, marginBottom: 14 },
  brand: { fontSize: 9, letterSpacing: 2, fontFamily: 'Helvetica-Bold' },
  title: { fontSize: 15, fontFamily: 'Helvetica-Bold' },
  meta: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12, color: C.muted },
  h2: { fontSize: 11, fontFamily: 'Helvetica-Bold', marginTop: 12, marginBottom: 6, color: C.ink },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderColor: C.line, paddingVertical: 3 },
  cell: { flex: 1 },
  cellSm: { width: 70 },
  hdr: { fontFamily: 'Helvetica-Bold', color: C.muted, fontSize: 8, textTransform: 'uppercase' },
  refl: { marginBottom: 6 },
  reflLabel: { fontSize: 8, color: C.muted, textTransform: 'uppercase', fontFamily: 'Helvetica-Bold' },
  footer: { position: 'absolute', bottom: 18, left: 28, right: 28, fontSize: 8, color: C.muted, textAlign: 'center' },
});

function Header({ title, sub }: { title: string; sub: string }) {
  return (
    <View style={s.band}>
      <Text style={s.brand}>VIKAS TOOL MART</Text>
      <Text style={s.title}>{title}</Text>
      <Text style={{ fontSize: 9, marginTop: 2 }}>{sub}</Text>
    </View>
  );
}

function DailyDoc({ r }: { r: DailyReport }) {
  const tasksDone = r.tasks.filter((t) => t.done).length;
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Header title="CRE Daily Report" sub={`${r.user.name} · ${r.date}${r.submitted ? ' · Submitted' : ''}`} />

        <Text style={s.h2}>KPIs</Text>
        <View style={s.row}>
          <Text style={[s.cell, s.hdr]}>KPI</Text>
          <Text style={[s.cellSm, s.hdr]}>Value</Text>
          <Text style={[s.cellSm, s.hdr]}>Source</Text>
          <Text style={[s.cellSm, s.hdr]}>Target</Text>
        </View>
        {r.kpis.map((k, i) => (
          <View style={s.row} key={i}>
            <Text style={s.cell}>{k.label}</Text>
            <Text style={s.cellSm}>{k.value ?? '-'}{k.unit ?? ''}</Text>
            <Text style={s.cellSm}>{k.source}</Text>
            <Text style={s.cellSm}>{k.target ?? '-'}</Text>
          </View>
        ))}

        <Text style={s.h2}>Tasks ({tasksDone}/{r.tasks.length})</Text>
        {r.tasks.map((t, i) => (
          <View style={s.row} key={i}>
            <Text style={s.cell}>{t.label}</Text>
            <Text style={[s.cellSm, { color: t.done ? C.green : C.muted }]}>{t.done ? 'Done' : '-'}</Text>
          </View>
        ))}

        <Text style={s.h2}>Social</Text>
        <View style={s.row}>
          <Text style={[s.cell, s.hdr]}>Channel</Text>
          <Text style={[s.cellSm, s.hdr]}>Yest.</Text>
          <Text style={[s.cellSm, s.hdr]}>Today</Text>
          <Text style={[s.cellSm, s.hdr]}>Change</Text>
        </View>
        {r.social.map((c, i) => (
          <View style={s.row} key={i}>
            <Text style={s.cell}>{c.name}</Text>
            <Text style={s.cellSm}>{c.yesterday ?? '-'}</Text>
            <Text style={s.cellSm}>{c.today ?? '-'}</Text>
            <Text style={s.cellSm}>{c.change ?? '-'}</Text>
          </View>
        ))}

        <Text style={s.h2}>Reflections</Text>
        {([
          ['Achievement', r.reflections.achievement],
          ['Issues', r.reflections.issues],
          ['Commitment', r.reflections.commitment],
          ['Notes', r.reflections.notes],
        ] as const).map(([label, val], i) => (
          <View style={s.refl} key={i}>
            <Text style={s.reflLabel}>{label}</Text>
            <Text>{val || '-'}</Text>
          </View>
        ))}

        <Text style={s.footer} fixed>
          Generated by VTM CROS ·{' '}
          <Link src="https://sirahdigital.in/" style={{ color: C.muted, textDecoration: 'none' }}>Sirah Digital</Link>
        </Text>
      </Page>
    </Document>
  );
}

function SummaryDoc({ r }: { r: SummaryReport }) {
  const metrics: Array<[string, string | number, string]> = [
    ['Average rating (/10)', r.avgRating.value ?? '-', r.avgRating.source],
    ['Reviews received', r.reviewsReceived.value ?? '-', r.reviewsReceived.source],
    ['Open complaints', r.complaintsOpen.value ?? '-', r.complaintsOpen.source],
    ['Resolved complaints', r.complaintsResolved.value ?? '-', r.complaintsResolved.source],
    ['New customers', r.newCustomers.value ?? '-', r.newCustomers.source],
    ['Repeat customers', r.repeatCustomers.value ?? '-', r.repeatCustomers.source],
    ['Follower growth', r.followerGrowth.value ?? '-', r.followerGrowth.source],
  ];
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Header title="Management Summary" sub={`${r.range.label} · generated ${r.generatedAt}`} />

        <Text style={s.h2}>Metrics</Text>
        <View style={s.row}>
          <Text style={[s.cell, s.hdr]}>Metric</Text>
          <Text style={[s.cellSm, s.hdr]}>Value</Text>
          <Text style={[s.cellSm, s.hdr]}>Source</Text>
        </View>
        {metrics.map(([label, value, source], i) => (
          <View style={s.row} key={i}>
            <Text style={s.cell}>{label}</Text>
            <Text style={s.cellSm}>{String(value)}</Text>
            <Text style={s.cellSm}>{source}</Text>
          </View>
        ))}

        <Text style={s.h2}>CRE Accountability</Text>
        <View style={s.row}>
          <Text style={[s.cell, s.hdr]}>CRE</Text>
          <Text style={[s.cellSm, s.hdr]}>Submitted</Text>
          <Text style={[s.cellSm, s.hdr]}>Tasks %</Text>
          <Text style={[s.cellSm, s.hdr]}>KPIs</Text>
        </View>
        {r.accountability.map((a, i) => (
          <View style={s.row} key={i}>
            <Text style={s.cell}>{a.name} ({a.role})</Text>
            <Text style={s.cellSm}>{a.submittedDays}</Text>
            <Text style={s.cellSm}>{a.tasksPct}%</Text>
            <Text style={s.cellSm}>{a.kpisFilledAvg}</Text>
          </View>
        ))}

        <Text style={s.footer} fixed>
          Generated by VTM CROS ·{' '}
          <Link src="https://sirahdigital.in/" style={{ color: C.muted, textDecoration: 'none' }}>Sirah Digital</Link>
        </Text>
      </Page>
    </Document>
  );
}

export function renderDailyPdf(report: DailyReport): Promise<Buffer> {
  return renderToBuffer(<DailyDoc r={report} />);
}

export function renderSummaryPdf(report: SummaryReport): Promise<Buffer> {
  return renderToBuffer(<SummaryDoc r={report} />);
}
